spring.application.name=u3w3d1
spring.config.import=file:env.properties
# SERVER
server.port=${PORT}
# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
# Cloudinary
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_API_SECRET}
jwt.secret=${JWT_SECRET}
